name: Clean-Workflow

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  Clean-Workflow:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
