name: Clean-Workflow


on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  Cleanup-Old-Artifacts:
    runs-on: ubuntu-18.04
    steps:
    - name: Cleanup Old Action Artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ github.token }}
        expire-in: 1d
  Cleanup-Workflow-Runs:
    needs: Cleanup-Old-Artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: Cleanup Workflow Runs
        uses: GitRML/delete-workflow-runs@v1.2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
