name: test

on:
  repository_dispatch:
  workflow_dispatch:
  

jobs:
  test_job: 
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%F-%H%M%S")-R2S-18.06"
        echo "::set-output name=release_date::$(date +"%F-%H%M%S")"
        touch  release.txt
        echo "::set-output name=status::success"
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ steps.tag.outputs.release_date }} R2S-18.06
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: |
          /etc/apt/*
